name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Books/Neukirch/Neukirch.tex
            Books/Neukirch/Notes.tex
            Exams/NumberTheory/Solutions/NumberTheory.tex
            Misc/Bernoulli/Bernoulli.tex
            Misc/Integral/Integral.tex
            Misc/Recurrence/Recurrence.tex
            Misc/pde/pde.tex
            Misc/Ufd/Ufd.tex
            Papers/GK/GK.tex
            MIT/Solutions/MIT.tex
      - name: Upload LaTeX document
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            Bernoulli.pdf
            Neukirch.pdf
            Notes.pdf
            NumberTheory.pdf
            Integral.pdf
            Recurrence.pdf
            pde.pdf
            GK.pdf
            Ufd.pdf
            MIT.pdf